
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: reserva_api
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: reserva_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reserva
      MYSQL_USER: reserva
      MYSQL_PASSWORD: reserva
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: reserva_redis
    ports:
      - "6390:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    container_name: reserva_nginx
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

  horizon:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: reserva_horizon
    command: php artisan horizon
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      - api
      - redis

  # Optional (add later when you switch to RabbitMQ):
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: reserva_rabbit
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql_data:
  redis_data:
  # rabbitmq_data:
